export enum Actions {
  // AUTH
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  PROFILE = 'PROFILE',

  // TRANSFER
  TRANSFER = 'TRANSFER',
  TRANSFER_TO_BANK_ACCOUNT = 'TRANSFER_TO_BANK_ACCOUNT',
  TRANSFER_TO_EMAIL = 'TRANSFER_TO_EMAIL',
  TRANSFER_TO_WALLET = 'TRANSFER_TO_WALLET',
  TRANSFER_HISTORY = 'TRANSFER_HISTORY',
  CONFIRM_EMAIL_TRANSFER = 'CONFIRM_EMAIL_TRANSFER',

  KYC = 'KYC',
  DEPOSIT = 'DEPOSIT',
  BALANCE = 'BALANCE',

  // WALLET
  WALLET = 'WALLET',
  SET_DEFAULT_WALLET = 'SET_DEFAULT_WALLET',

  // PAYEE
  PAYEE = 'PAYEE',
  ADD_PAYEE = 'ADD_PAYEE',
  REMOVE_PAYEE = 'REMOVE_PAYEE',

  // REFERRALS
  REFERRALS = 'REFERRALS',
  VALIDATE_REFERRAL = 'VALIDATE_REFERRAL',

  // TRANSACTIONS
  TRANSACTIONS = 'TRANSACTIONS',

  // POINTS
  POINTS = 'POINTS',

  // MISC
  CLOSE = 'CLOSE',
}
