export enum Commands {
  Login = 'login',
  Logout = 'logout',
  Deposit = 'deposit',
  Profile = 'profile',
  Close = 'close',
  Cancel = 'cancel',
  KYC = 'kyc',
  PAYEE = 'recipients',
  ADD_PAYEE = 'add_recipient',
  REMOVE_PAYEE = 'remove_recipient',
  POINTS = 'points',
  REFERRALS = 'referrals',
  TRANSFER = 'transfer',
  TRANSFER_TO_EMAIL = 'transfer_to_email',
  TRANSFER_TO_WALLET = 'transfer_to_wallet',
  TRANSFER_TO_BANK_ACCOUNT = 'transfer_to_bank_account',
  TRANSFER_HISTORY = 'transfer_history',
  WALLET = 'wallet',
  SET_DEFAULT_WALLET = 'set_default_wallet',
  TRANSACTIONS = 'transactions',
  HELP = 'help',
  MAIN_MENU = 'main_menu',
}
